#!/usr/bin/env node
/**
 * Gemini 自动发文脚本
 * 用法:
 *   GEMINI_API_KEY=xxx node scripts/generate-article.mjs
 *   node scripts/generate-article.mjs --count=3
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenerativeAI } from "@google/generative-ai";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const postsDir = path.join(__dirname, "../src/posts");
const indexNowManifest = path.join(__dirname, ".indexnow-pending.json");

const TAG_POOL = [
  "快连下载", "Windows", "macOS", "Android", "iOS", "安装教程", "连接",
  "节点", "延迟", "更新", "排错", "账号", "隐私", "企业", "平板", "游戏"
];
const CATEGORY_POOL = ["使用教程", "版本动态", "常见问题", "资源百科"];

function parseArgs() {
  const countArg = process.argv.find((a) => a.startsWith("--count="));
  const positional = process.argv[2];
  let count = countArg
    ? parseInt(countArg.split("=")[1], 10)
    : positional && !positional.startsWith("-")
      ? parseInt(positional, 10)
      : 1;
  if (Number.isNaN(count) || count < 1) count = 1;
  if (count > 9) count = 9;
  return count;
}

function slugify(str) {
  const base =
    String(str)
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .replace(/[\u4e00-\u9fff]/g, "")
      .replace(/-+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "kuailian";
  return `${base}-${Date.now().toString(36)}`;
}

function pickTags(n = 3) {
  const shuffled = [...TAG_POOL].sort(() => Math.random() - 0.5);
  const tags = new Set(["快连下载"]);
  for (const t of shuffled) {
    if (tags.size >= n) break;
    tags.add(t);
  }
  return [...tags];
}

function imgUrl(q) {
  return `https://tse-mm.bing.com/th?q=${encodeURIComponent(q)}`;
}

async function generateOne(genAI) {
  const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
  const category = CATEGORY_POOL[Math.floor(Math.random() * CATEGORY_POOL.length)];
  const tags = pickTags(3 + Math.floor(Math.random() * 2));

  const prompt = `你是技术教程作者。请写一篇关于「快连下载」的中文原创文章，适合发布在客户端下载指南网站。

要求：
1. 标题自然包含「快连下载」，15-30字，不要夸张营销语
2. 正文 800-1200 字，分 3-4 个小节，使用 Markdown
3. 内容围绕：${category}，并延伸快连下载相关场景
4. 禁止出现：seo、关键词、优化、排名、收录、曝光、爬虫、算法
5. 禁止外链，文末延伸阅读只用站内链接文字：快连下载教程大全(/blog/)、快连官方下载中心(/download.html)、快连下载首页(/)
6. 提供 description 字段 80-120 字
7. 提供 imageKeyword1 和 imageKeyword2（用于配图，各 4-8 字，与快连下载相关）
8. 只输出 JSON，格式：
{"title":"","description":"","bodyMarkdown":"## 小节\\n\\n段落..."}

bodyMarkdown 中在合适位置插入两行图片占位：
![描述](IMAGE1)
![描述](IMAGE2)
不要写其他字段。`;

  const result = await model.generateContent(prompt);
  const text = result.response.text().replace(/```json|```/g, "").trim();
  const data = JSON.parse(text);

  const img1 = data.imageKeyword1 || "快连下载 教程";
  const img2 = data.imageKeyword2 || "快连下载 客户端";
  let body = data.bodyMarkdown
    .replace("IMAGE1", imgUrl(img1))
    .replace("IMAGE2", imgUrl(img2));

  if (!body.includes("![")) {
    body = `![${img1}](${imgUrl(img1)})\n\n${body}\n\n![${img2}](${imgUrl(img2)})`;
  }

  const slug = slugify(data.title);
  const date = new Date().toISOString().slice(0, 10);
  const fm = `---
layout: layouts/post.njk
title: ${data.title.replace(/"/g, '\\"')}
description: ${data.description.replace(/"/g, '\\"')}
category: ${category}
tags:
${tags.map((t) => `  - ${t}`).join("\n")}
date: ${date}
permalink: /posts/${slug}/
autoGenerated: true
---

${body}
`;

  const file = path.join(postsDir, `${slug}.md`);
  fs.mkdirSync(postsDir, { recursive: true });
  fs.writeFileSync(file, fm, "utf8");
  return { file, permalink: `/posts/${slug}/`, date };
}

async function main() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.error("请设置环境变量 GEMINI_API_KEY");
    process.exit(1);
  }
  const count = parseArgs();
  const genAI = new GoogleGenerativeAI(apiKey);
  const created = [];
  for (let i = 0; i < count; i++) {
    console.log(`生成第 ${i + 1}/${count} 篇...`);
    created.push(await generateOne(genAI));
    if (i < count - 1) await new Promise((r) => setTimeout(r, 2000));
  }

  const today = new Date().toISOString().slice(0, 10);
  let manifest = { date: today, permalinks: [] };
  if (fs.existsSync(indexNowManifest)) {
    try {
      const old = JSON.parse(fs.readFileSync(indexNowManifest, "utf8"));
      if (old.date === today && Array.isArray(old.permalinks)) {
        manifest.permalinks = old.permalinks;
      }
    } catch {}
  }
  for (const item of created) {
    if (!manifest.permalinks.includes(item.permalink)) {
      manifest.permalinks.push(item.permalink);
    }
  }
  fs.writeFileSync(indexNowManifest, JSON.stringify(manifest, null, 2), "utf8");
  console.log("IndexNow 待推送:", manifest.permalinks.join(", "));
  console.log(
    "完成:",
    created.map((x) => x.file).join("\n")
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
